/* eslint-disable @next/next/no-img-element -- private authenticated signature image */
import { notFound } from "next/navigation";
import { prisma } from "@/lib/prisma";
import { PrintButton } from "@/components/print-button";
import { formatDateTime } from "@/lib/utils";

export const dynamic = "force-dynamic";
type ManifestItem = { name?: string; status?: string; reference?: string };
export default async function VehicleAcknowledgementPrintPage({ params }: { params: Promise<{ ackId: string }> }) {
  const { ackId } = await params;
  const [ack, setting] = await Promise.all([prisma.vehicleDocumentAcknowledgement.findUnique({ where: { id: ackId }, include: { case: { include: { sale: { select: { saleNumber: true, vehicleLabelSnapshot: true, engineNumberSnapshot: true, chassisNumberSnapshot: true } } } }, witnessedBy: { select: { name: true } } } }), prisma.setting.findUnique({ where: { id: 1 } })]);
  if (!ack) notFound();
  const manifest = Array.isArray(ack.documentManifest) ? ack.documentManifest as ManifestItem[] : [];
  return <div className="mx-auto max-w-3xl"><div className="no-print mb-4 flex justify-end"><PrintButton label="Print acknowledgement" /></div><article className="print-area print-a4 rounded-xl border border-border bg-surface p-8 shadow-sm"><header className="flex items-start justify-between gap-5 border-b border-border pb-5"><div><h1 className="text-2xl font-extrabold">{setting?.businessName ?? "Madagama Pvt Ltd"}</h1><p className="text-sm text-muted">{setting?.address}</p></div><div className="text-right"><h2 className="max-w-xs text-lg font-bold">{ack.type === "CUSTOMER_DOCUMENTS_RECEIVED" ? "CUSTOMER DOCUMENTS RECEIVED" : "REGISTRATION DOCUMENTS HANDED OVER"}</h2><p className="font-mono text-sm">VS-{String(ack.case.sale.saleNumber).padStart(6, "0")}</p></div></header><section className="grid grid-cols-2 gap-5 py-5 text-sm"><div><p className="text-xs uppercase tracking-wide text-muted">Vehicle</p><p className="mt-1 font-bold">{ack.case.sale.vehicleLabelSnapshot}</p><p>Engine: <span className="font-mono">{ack.case.sale.engineNumberSnapshot}</span></p><p>Chassis: <span className="font-mono">{ack.case.sale.chassisNumberSnapshot}</span></p></div><div className="text-right"><p className="text-xs uppercase tracking-wide text-muted">Customer</p><p className="mt-1 font-bold">{ack.signerName}</p><p>NIC: <span className="font-mono">{ack.signerNic}</span></p><p>{formatDateTime(ack.signedAt)}</p></div></section><p className="rounded-lg border border-border bg-input/40 p-4 text-sm leading-6">{ack.acknowledgementText}</p><table className="mt-5 w-full text-sm"><thead><tr className="border-y border-border text-left text-muted"><th className="py-2">Document</th><th>Status</th><th>Reference</th></tr></thead><tbody>{manifest.map((item, index) => <tr key={index} className="border-b border-border-subtle"><td className="py-2">{item.name ?? "Document"}</td><td>{item.status?.replaceAll("_", " ") ?? "—"}</td><td className="font-mono text-xs">{item.reference || "—"}</td></tr>)}</tbody></table><div className="mt-10 grid grid-cols-2 gap-12"><div><p className="mb-2 text-xs text-muted">Customer signature</p>{ }<img src={`/api/files/${ack.signatureKey}`} alt="Customer signature" className="h-28 w-full object-contain object-left" /><div className="border-t border-border pt-2 text-xs">{ack.signerName}</div></div><div className="flex flex-col justify-end"><div className="border-t border-border pt-2 text-xs">Witnessed by {ack.witnessedBy?.name ?? "Madagama staff"}</div></div></div><p className="mt-10 break-all border-t border-border pt-3 font-mono text-[9px] text-faint">Manifest integrity: {ack.manifestHash}</p></article></div>;
}
