import Link from "next/link";
import { notFound } from "next/navigation";
import { Banknote, Building2, CheckCircle2, ClipboardCheck, FileText, HandCoins, Printer, Tractor, UserRound } from "lucide-react";
import { prisma } from "@/lib/prisma";
import { getSession } from "@/lib/auth";
import { canAccessStaffFinance } from "@/lib/authorization";
import { PageHeader } from "@/components/page-header";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Table, TBody, TD, TH, THead, TR } from "@/components/ui/table";
import { VehiclePaymentForm } from "@/components/vehicle-payment-form";
import { VehicleSupplierSettlementForm } from "@/components/vehicle-supplier-settlement-form";
import { VehicleDossierMasthead } from "@/components/vehicle-dossier-masthead";
import { recordVehicleCustomerPayment, recordVehicleSupplierSettlement } from "../actions";
import { formatDate, formatLKR, toNum } from "@/lib/utils";
import { computeCreditState } from "@/lib/credit";

export const dynamic = "force-dynamic";
const saleTypeLabel = { CASH: "Cash sale", EXTERNAL_FINANCE: "External finance", IN_HOUSE_CREDIT: "In-house credit" } as const;
export default async function VehicleSaleDetailPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ new?: string }> }) {
  const { id } = await params; const sp = await searchParams;
  const [sale, session] = await Promise.all([prisma.vehicleSale.findUnique({ where: { id }, include: { vehicle: { select: { id: true, kind: true } }, customer: { select: { id: true, name: true, phone: true, address: true } }, soldBy: { select: { name: true } }, payments: { orderBy: { paidDate: "desc" }, include: { recordedBy: { select: { name: true } } } }, creditAgreement: true, supplierSettlements: { orderBy: { paidDate: "desc" }, include: { recordedBy: { select: { name: true } } } }, documentCase: { include: { items: { select: { status: true, required: true } }, acknowledgements: { select: { type: true } } } } } }), getSession()]);
  if (!sale) notFound();
  const creditState = sale.creditAgreement ? computeCreditState({ principal: toNum(sale.creditAgreement.principal), startDate: sale.creditAgreement.startDate, interestRatePerMonth: toNum(sale.creditAgreement.interestRatePerMonth), interestFreeMonths: sale.creditAgreement.interestFreeMonths }, sale.payments.filter((payment) => ["INSTALLMENT", "FINAL_SETTLEMENT"].includes(payment.kind)).map((payment) => ({ amount: toNum(payment.amount), paidDate: payment.paidDate })), new Date()) : null;
  const customerOutstanding = sale.type === "EXTERNAL_FINANCE" ? 0 : Math.max(0, creditState?.outstanding ?? (toNum(sale.customerPrice) - toNum(sale.customerCollected)));
  const supplierOutstanding = Math.max(0, toNum(sale.supplierSettlementDue) - toNum(sale.supplierPaid));
  const documentOutstanding = sale.documentCase?.items.filter((i) => i.required && i.status === "REQUIRED").length ?? 0;
  const isAdmin = session ? canAccessStaffFinance(session.role) : false;
  return <div className="mx-auto max-w-6xl">{sp.new ? <div className="mb-4 flex items-center gap-2 rounded-xl bg-primary-soft px-4 py-3 text-sm text-primary-ink"><CheckCircle2 className="h-5 w-5" />Vehicle sale confirmed. Commercial terms are now locked.</div> : null}<PageHeader title={`VS-${String(sale.saleNumber).padStart(6, "0")}`} subtitle={`${sale.vehicleLabelSnapshot} · ${saleTypeLabel[sale.type]}`} action={<div className="flex flex-wrap gap-2"><Link href={`/vehicle-sales/${sale.id}/print`}><Button variant="outline"><Printer className="h-4 w-4" />{sale.type === "EXTERNAL_FINANCE" ? "Print down-payment receipt" : "Print sale bill"}</Button></Link>{sale.documentCase ? <Link href={`/vehicle-sales/${sale.id}/documents`}><Button><ClipboardCheck className="h-4 w-4" />Documents</Button></Link> : null}</div>} />
    <VehicleDossierMasthead label={sale.vehicleLabelSnapshot} status={sale.status} engineNumber={sale.engineNumberSnapshot} chassisNumber={sale.chassisNumberSnapshot} supplier={sale.supplierNameSnapshot} compact />
    <div className="mb-4 grid grid-cols-1 gap-3 min-[440px]:grid-cols-2 lg:grid-cols-4"><Summary label="Customer price" value={toNum(sale.customerPrice)} icon={Banknote} /><Summary label="Customer outstanding" value={customerOutstanding} tone={customerOutstanding > 0 ? "amber" : "green"} /><Summary label="Supplier outstanding" value={supplierOutstanding} tone={supplierOutstanding > 0 ? "amber" : "green"} /><Summary label="Net commission" value={toNum(sale.netDealerCommission)} tone="blue" /></div>
    <div className="grid grid-cols-1 gap-4 lg:grid-cols-3"><div className="space-y-4 lg:col-span-2">
      <Card><CardHeader><CardTitle>Financial split</CardTitle></CardHeader><CardContent className="grid grid-cols-1 gap-4 sm:grid-cols-2"><div className="space-y-2 text-sm tabular-nums"><Money label="List price" value={toNum(sale.listPrice)} /><Money label="Customer discount" value={toNum(sale.customerDiscount)} /><Money label="Customer price" value={toNum(sale.customerPrice)} strong /></div><div className="space-y-2 border-t border-border-subtle pt-4 text-sm tabular-nums sm:border-l sm:border-t-0 sm:pl-4 sm:pt-0"><Money label="Supplier amount" value={toNum(sale.supplierSettlementDue)} /><Money label="Gross commission" value={toNum(sale.grossDealerCommission)} /><Money label="Net commission" value={toNum(sale.netDealerCommission)} strong /></div></CardContent></Card>
      <Card><CardHeader className="flex items-center justify-between"><CardTitle>Customer collections</CardTitle><Badge tone={customerOutstanding <= 0 ? "green" : "amber"}>{customerOutstanding <= 0 ? "Fully collected" : `${formatLKR(customerOutstanding)} due`}</Badge></CardHeader><CardContent className="p-0">{sale.payments.length === 0 ? <p className="px-5 py-10 text-center text-sm text-muted">No customer payments recorded.</p> : <><div className="divide-y divide-border-subtle md:hidden">{sale.payments.map((p) => <Link key={p.id} href={`/vehicle-sales/${sale.id}/receipts/${p.id}`} className="flex items-start justify-between gap-3 p-4"><div><p className="font-mono text-xs font-bold text-primary">VREC-{String(p.receiptNumber).padStart(6, "0")}</p><p className="mt-1 text-xs text-muted">{formatDate(p.paidDate)} · {p.kind.replaceAll("_", " ")} · {p.method}</p>{p.reference ? <p className="mt-1 break-all font-mono text-xs text-muted">{p.reference}</p> : null}</div><p className="shrink-0 font-bold tabular-nums">{formatLKR(p.amount)}</p></Link>)}</div><div className="hidden md:block"><Table><THead><TR><TH>Receipt</TH><TH>Date</TH><TH>Kind / method</TH><TH>Reference</TH><TH className="text-right">Amount</TH></TR></THead><TBody>{sale.payments.map((p) => <TR key={p.id}><TD><Link className="font-mono text-xs font-semibold text-primary hover:underline" href={`/vehicle-sales/${sale.id}/receipts/${p.id}`}>VREC-{String(p.receiptNumber).padStart(6, "0")}</Link></TD><TD>{formatDate(p.paidDate)}</TD><TD><span className="text-xs">{p.kind.replaceAll("_", " ")} · {p.method}</span></TD><TD className="font-mono text-xs text-muted">{p.reference ?? "—"}</TD><TD className="text-right font-semibold tabular-nums">{formatLKR(p.amount)}</TD></TR>)}</TBody></Table></div></>}</CardContent></Card>
      {session?.role !== "SALESPERSON" && sale.type === "IN_HOUSE_CREDIT" && customerOutstanding > 0 && sale.status === "CONFIRMED" ? <Card><CardHeader><CardTitle>Collect installment</CardTitle></CardHeader><CardContent><VehiclePaymentForm action={recordVehicleCustomerPayment.bind(null, sale.id)} outstanding={customerOutstanding} /></CardContent></Card> : null}
      <Card><CardHeader className="flex items-center justify-between"><CardTitle>Supplier settlements</CardTitle><Badge tone={supplierOutstanding <= 0 ? "green" : "amber"}>{supplierOutstanding <= 0 ? "Paid" : `${formatLKR(supplierOutstanding)} due`}</Badge></CardHeader><CardContent className="p-0">{sale.supplierSettlements.length === 0 ? <p className="px-5 py-10 text-center text-sm text-muted">No supplier settlements recorded.</p> : <><div className="divide-y divide-border-subtle md:hidden">{sale.supplierSettlements.map((p) => <div key={p.id} className="flex items-start justify-between gap-3 p-4"><div><p className="text-xs font-semibold">{formatDate(p.paidDate)} · {p.method}</p><p className="mt-1 break-all font-mono text-xs text-muted">{p.reference ?? "No reference"}</p><p className="mt-1 text-xs text-muted">Recorded by {p.recordedBy?.name ?? "—"}</p></div><p className="shrink-0 font-bold tabular-nums">{formatLKR(p.amount)}</p></div>)}</div><div className="hidden md:block"><Table><THead><TR><TH>Date</TH><TH>Method</TH><TH>Reference</TH><TH>Recorded by</TH><TH className="text-right">Amount</TH></TR></THead><TBody>{sale.supplierSettlements.map((p) => <TR key={p.id}><TD>{formatDate(p.paidDate)}</TD><TD>{p.method}</TD><TD className="font-mono text-xs text-muted">{p.reference ?? "—"}</TD><TD className="text-muted">{p.recordedBy?.name ?? "—"}</TD><TD className="text-right font-semibold tabular-nums">{formatLKR(p.amount)}</TD></TR>)}</TBody></Table></div></>}</CardContent></Card>
      {isAdmin && supplierOutstanding > 0 && sale.status === "CONFIRMED" ? <Card><CardHeader><CardTitle>Pay supplier</CardTitle></CardHeader><CardContent><VehicleSupplierSettlementForm action={recordVehicleSupplierSettlement.bind(null, sale.id)} outstanding={supplierOutstanding} supplierName={sale.supplierNameSnapshot} /></CardContent></Card> : null}
    </div><aside className="space-y-4"><Card><CardHeader><CardTitle className="flex items-center gap-2"><Tractor className="h-4 w-4 text-muted" />Vehicle</CardTitle></CardHeader><CardContent className="space-y-3 text-sm"><Link href={`/vehicles/${sale.vehicle.id}`} className="font-semibold text-primary hover:underline">{sale.vehicleLabelSnapshot}</Link><Field label="Engine" value={sale.engineNumberSnapshot} mono /><Field label="Chassis" value={sale.chassisNumberSnapshot} mono /></CardContent></Card><Card><CardHeader><CardTitle className="flex items-center gap-2"><UserRound className="h-4 w-4 text-muted" />Customer</CardTitle></CardHeader><CardContent className="space-y-2 text-sm"><Link href={`/customers/${sale.customer.id}`} className="font-semibold text-primary hover:underline">{sale.customer.name}</Link><p className="text-muted">{sale.customer.phone}</p><p className="text-muted">{sale.customer.address ?? "No address recorded"}</p></CardContent></Card>{sale.type === "EXTERNAL_FINANCE" ? <Card><CardHeader><CardTitle className="flex items-center gap-2"><Building2 className="h-4 w-4 text-muted" />Finance provider</CardTitle></CardHeader><CardContent className="space-y-2 text-sm"><Field label="Provider" value={sale.financeProvider ?? "—"} /><Field label="Reference" value={sale.financeReference ?? "—"} mono /><Money label="Approved amount" value={toNum(sale.financeApprovedAmount)} /></CardContent></Card> : null}{sale.creditAgreement ? <Card><CardHeader><CardTitle>Credit terms</CardTitle></CardHeader><CardContent className="space-y-2 text-sm"><Field label="Status" value={sale.creditAgreement.status} /><Field label="First due" value={formatDate(sale.creditAgreement.firstDueDate)} /><Field label="Term" value={sale.creditAgreement.termMonths ? `${sale.creditAgreement.termMonths} months` : "—"} /><Money label="Expected installment" value={toNum(sale.creditAgreement.expectedInstallment)} /></CardContent></Card> : null}<Card><CardHeader><CardTitle className="flex items-center gap-2"><FileText className="h-4 w-4 text-muted" />Registration documents</CardTitle></CardHeader><CardContent><div className="flex items-center justify-between gap-3"><div><Badge tone={sale.documentCase?.status === "HANDED_OVER" ? "green" : "amber"}>{sale.documentCase?.status.replaceAll("_", " ") ?? "NOT STARTED"}</Badge><p className="mt-2 text-xs text-muted">{documentOutstanding} required item{documentOutstanding === 1 ? "" : "s"} outstanding</p></div>{sale.documentCase ? <Link href={`/vehicle-sales/${sale.id}/documents`}><Button size="sm" variant="outline">Open</Button></Link> : null}</div></CardContent></Card><Card><CardContent className="space-y-1 py-4 text-xs text-muted"><p>Sold {formatDate(sale.saleDate)}</p><p>Salesperson {sale.soldBy?.name ?? "—"}</p><p>Supplier {sale.supplierNameSnapshot}</p></CardContent></Card></aside></div>
  </div>;
}
function Summary({ label, value, tone = "default", icon: Icon = HandCoins }: { label: string; value: number; tone?: "default" | "amber" | "green" | "blue"; icon?: React.ElementType }) { const tones = { default: "border-l-slate-400", amber: "border-l-amber-500 bg-amber-50/50 dark:bg-amber-950/20", green: "border-l-emerald-500 bg-emerald-50/50 dark:bg-emerald-950/20", blue: "border-l-blue-500 bg-blue-50/50 dark:bg-blue-950/20" }; return <div className={`rounded-2xl border border-border border-l-4 ${tones[tone]} p-4`}><div className="flex items-center justify-between gap-2"><p className="text-xs font-medium text-muted">{label}</p><Icon className="h-4 w-4 text-muted" /></div><p className="mt-2 break-words text-lg font-extrabold tabular-nums">{formatLKR(value)}</p></div>; }
function Money({ label, value, strong }: { label: string; value: number; strong?: boolean }) { return <div className="flex items-center justify-between gap-3"><span className={strong ? "font-semibold" : "text-muted"}>{label}</span><span className={strong ? "font-bold text-primary-ink" : "font-semibold"}>{formatLKR(value)}</span></div>; }
function Field({ label, value, mono }: { label: string; value: string; mono?: boolean }) { return <div><p className="text-xs text-faint">{label}</p><p className={mono ? "break-all font-mono text-xs font-semibold" : "font-medium"}>{value}</p></div>; }
