/* eslint-disable @next/next/no-img-element -- private authenticated vehicle images */
import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowRight, CheckCircle2, ClipboardList, HandCoins, Pencil, Tractor } from "lucide-react";
import { prisma } from "@/lib/prisma";
import { getSession } from "@/lib/auth";
import { PageHeader } from "@/components/page-header";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { VehicleDossierMasthead } from "@/components/vehicle-dossier-masthead";
import { formatDate, formatLKR, toNum } from "@/lib/utils";

export const dynamic = "force-dynamic";
const kindLabel = { TRACTOR: "Tractor", HARVESTER: "Harvester", COMBINE_HARVESTER: "Combine harvester" } as const;
const statusTone = { DRAFT: "gray", AVAILABLE: "green", RESERVED: "amber", SOLD: "blue", RETURNED: "gray" } as const;
export default async function VehicleDetailPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ new?: string }> }) {
  const { id } = await params; const sp = await searchParams;
  const [vehicle, session] = await Promise.all([prisma.consignmentVehicle.findUnique({ where: { id }, include: { supplier: { select: { id: true, name: true, phone: true } }, receivedBy: { select: { name: true } }, sales: { orderBy: { saleDate: "desc" }, include: { customer: { select: { name: true } } } } } }), getSession()]);
  if (!vehicle) notFound();
  const gross = toNum(vehicle.listPrice) - toNum(vehicle.supplierSettlementDue);
  const activeSale = vehicle.sales.find((s) => s.status === "CONFIRMED");
  return <div className="mx-auto max-w-5xl">{sp.new ? <div className="mb-4 flex items-center gap-2 rounded-xl bg-primary-soft px-4 py-3 text-sm text-primary-ink"><CheckCircle2 className="h-5 w-5" />Vehicle received into consignment inventory.</div> : null}<PageHeader title={`${vehicle.make} ${vehicle.model}`} subtitle={`${kindLabel[vehicle.kind]} · Vehicle #${String(vehicle.vehicleNumber).padStart(6, "0")}`} action={<div className="flex flex-wrap gap-2">{session?.role === "ADMIN" && vehicle.status !== "SOLD" ? <Link href={`/vehicles/${vehicle.id}/edit`}><Button variant="outline"><Pencil className="h-4 w-4" />Edit</Button></Link> : null}{vehicle.status === "AVAILABLE" && session?.role !== "SALESPERSON" ? <Link href={`/vehicle-sales/new?vehicle=${vehicle.id}`}><Button>Start sale <ArrowRight className="h-4 w-4" /></Button></Link> : activeSale ? <Link href={`/vehicle-sales/${activeSale.id}`}><Button variant="outline">View sale <ArrowRight className="h-4 w-4" /></Button></Link> : null}</div>} />
    <VehicleDossierMasthead vehicleNumber={`#${String(vehicle.vehicleNumber).padStart(6, "0")}`} label={`${vehicle.make} ${vehicle.model}`} kind={kindLabel[vehicle.kind]} status={vehicle.status} engineNumber={vehicle.engineNumber} chassisNumber={vehicle.chassisNumber} supplier={vehicle.supplier.name} />
    <div className="grid grid-cols-1 gap-4 lg:grid-cols-3"><div className="space-y-4 lg:col-span-2"><Card><CardHeader className="flex items-center justify-between"><CardTitle className="flex items-center gap-2"><Tractor className="h-4 w-4 text-muted" />Vehicle identity</CardTitle><Badge tone={statusTone[vehicle.status]}>{vehicle.status}</Badge></CardHeader><CardContent className="grid grid-cols-2 gap-x-5 gap-y-4 text-sm"><Field label="Type" value={kindLabel[vehicle.kind]} /><Field label="Year / colour" value={[vehicle.year, vehicle.colour].filter(Boolean).join(" · ") || "—"} /><Field label="Engine number" value={vehicle.engineNumber} mono /><Field label="Chassis number" value={vehicle.chassisNumber} mono /><Field label="Received" value={formatDate(vehicle.receivedAt)} /><Field label="Supplier reference" value={vehicle.supplierReference ?? "—"} mono /></CardContent></Card>
      <Card><CardHeader><CardTitle className="flex items-center gap-2"><ClipboardList className="h-4 w-4 text-muted" />Specifications &amp; notes</CardTitle></CardHeader><CardContent className="space-y-4 text-sm"><div><p className="text-xs text-faint">Specifications / condition</p><p className="mt-1 whitespace-pre-wrap">{vehicle.specifications || "No specifications recorded."}</p></div>{vehicle.notes ? <div><p className="text-xs text-faint">Internal notes</p><p className="mt-1 whitespace-pre-wrap text-muted">{vehicle.notes}</p></div> : null}</CardContent></Card>
      {vehicle.photoKeys.length > 0 ? <Card><CardHeader><CardTitle>Vehicle photos</CardTitle></CardHeader><CardContent><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{vehicle.photoKeys.map((key) => <a key={key} href={`/api/files/${key}`} target="_blank" rel="noreferrer" className="overflow-hidden rounded-xl border border-border bg-input"><img src={`/api/files/${key}`} alt={`${vehicle.make} ${vehicle.model}`} className="aspect-square w-full object-cover" /></a>)}</div></CardContent></Card> : null}
      <Card><CardHeader><CardTitle>Sale history</CardTitle></CardHeader><CardContent>{vehicle.sales.length === 0 ? <p className="py-4 text-center text-sm text-muted">This vehicle has not been sold.</p> : <div className="divide-y divide-border-subtle">{vehicle.sales.map((sale) => <Link href={`/vehicle-sales/${sale.id}`} key={sale.id} className="flex items-center justify-between gap-3 py-3 first:pt-0 last:pb-0 hover:text-primary"><div><p className="text-sm font-semibold">VS-{String(sale.saleNumber).padStart(6, "0")} · {sale.customer.name}</p><p className="text-xs text-muted">{formatDate(sale.saleDate)} · {sale.type.replaceAll("_", " ")}</p></div><Badge tone={sale.status === "CONFIRMED" ? "green" : "red"}>{sale.status}</Badge></Link>)}</div>}</CardContent></Card></div>
      <aside className="space-y-4"><Card><CardHeader><CardTitle className="flex items-center gap-2"><HandCoins className="h-4 w-4 text-muted" />Commercial terms</CardTitle></CardHeader><CardContent className="space-y-3 text-sm tabular-nums"><Money label="List price" value={toNum(vehicle.listPrice)} /><Money label="Supplier payable after sale" value={toNum(vehicle.supplierSettlementDue)} /><div className="border-t border-border-subtle pt-3"><Money label="Gross dealer commission" value={gross} strong /></div><p className="pt-1 text-xs text-muted">Customer discounts reduce this commission. Terms are frozen when a sale is confirmed.</p></CardContent></Card><Card><CardHeader><CardTitle>Supplier</CardTitle></CardHeader><CardContent className="text-sm"><Link href={`/suppliers/${vehicle.supplier.id}`} className="font-semibold text-primary hover:underline">{vehicle.supplier.name}</Link><p className="mt-1 text-muted">{vehicle.supplier.phone ?? "No phone recorded"}</p></CardContent></Card><Card><CardContent className="space-y-1 py-4 text-xs text-muted"><p>Received by {vehicle.receivedBy?.name ?? "—"}</p><p>Created {formatDate(vehicle.createdAt)}</p></CardContent></Card></aside></div>
  </div>;
}
function Field({ label, value, mono }: { label: string; value: string; mono?: boolean }) { return <div><p className="text-xs text-faint">{label}</p><p className={mono ? "mt-0.5 break-all font-mono font-medium" : "mt-0.5 font-medium"}>{value}</p></div>; }
function Money({ label, value, strong }: { label: string; value: number; strong?: boolean }) { return <div className="flex items-center justify-between gap-3"><span className={strong ? "font-semibold" : "text-muted"}>{label}</span><span className={strong ? "font-bold text-primary-ink" : "font-semibold"}>{formatLKR(value)}</span></div>; }
