"use client";

import { useId, useMemo, useRef, useState } from "react";
import { ChevronDown, Search } from "lucide-react";

export function VehicleCombobox({ id, label, options, value, onChange, placeholder = "Select…" }: { id?: string; label: string; options: { value: string; label: string; hint?: string }[]; value: string; onChange: (value: string) => void; placeholder?: string }) {
  const generated = useId(); const base = id ?? generated; const buttonRef = useRef<HTMLButtonElement>(null); const [open, setOpen] = useState(false); const [query, setQuery] = useState(""); const [active, setActive] = useState(0);
  const filtered = useMemo(() => { const q = query.toLowerCase().trim(); return q ? options.filter((o) => `${o.label} ${o.hint ?? ""}`.toLowerCase().includes(q)) : options; }, [options, query]);
  const selected = options.find((o) => o.value === value);
  function pick(next: string) { onChange(next); setOpen(false); setQuery(""); }
  function handleKeys(event: React.KeyboardEvent) {
    if (event.key === "ArrowDown") { event.preventDefault(); setOpen(true); setActive((index) => Math.min(index + 1, Math.max(0, filtered.length - 1))); }
    else if (event.key === "ArrowUp") { event.preventDefault(); setActive((index) => Math.max(0, index - 1)); }
    else if (event.key === "Enter" && open && filtered[active]) { event.preventDefault(); pick(filtered[active].value); buttonRef.current?.focus(); }
    else if (event.key === "Escape" && open) { event.preventDefault(); setOpen(false); buttonRef.current?.focus(); }
  }
  return <div className="relative"><label id={`${base}-label`} className="mb-1.5 block text-sm font-medium text-foreground">{label}</label><button ref={buttonRef} id={base} type="button" role="combobox" aria-haspopup="listbox" aria-expanded={open} aria-controls={`${base}-listbox`} aria-labelledby={`${base}-label ${base}`} aria-activedescendant={open && filtered[active] ? `${base}-option-${active}` : undefined} onClick={() => setOpen((v) => !v)} onKeyDown={handleKeys} className="flex h-11 w-full items-center justify-between rounded-xl border border-input-border bg-input px-3.5 text-left text-sm outline-none focus:border-primary focus:ring-2 focus:ring-primary/20"><span className={selected ? "text-foreground" : "text-faint"}>{selected?.label ?? placeholder}</span><ChevronDown className="h-4 w-4 text-muted" /></button>{open ? <div className="absolute z-40 mt-1 w-full overflow-hidden rounded-xl border border-border bg-surface shadow-lg"><div className="relative border-b border-border p-2"><Search className="absolute left-4 top-1/2 h-4 w-4 -translate-y-1/2 text-muted" /><label className="sr-only" htmlFor={`${base}-search`}>Search {label.toLowerCase()}</label><input id={`${base}-search`} autoFocus value={query} aria-controls={`${base}-listbox`} aria-activedescendant={filtered[active] ? `${base}-option-${active}` : undefined} onKeyDown={handleKeys} onChange={(e) => { setQuery(e.target.value); setActive(0); }} className="h-9 w-full rounded-lg border border-input-border bg-input pl-8 pr-3 text-sm outline-none focus:border-primary" /></div><ul id={`${base}-listbox`} role="listbox" aria-labelledby={`${base}-label`} className="max-h-64 overflow-y-auto py-1">{filtered.length ? filtered.map((option, index) => <li key={option.value} id={`${base}-option-${index}`} role="option" aria-selected={option.value === value} className={index === active ? "bg-input" : undefined}><button type="button" className="flex w-full justify-between gap-3 px-3.5 py-2 text-left text-sm" onMouseEnter={() => setActive(index)} onClick={() => pick(option.value)}><span>{option.label}</span>{option.hint ? <span className="text-xs text-muted">{option.hint}</span> : null}</button></li>) : <li className="px-3.5 py-3 text-sm text-muted">No matches.</li>}</ul></div> : null}</div>;
}
