import Link from "next/link";
import { notFound } from "next/navigation";
import { CalendarClock, CheckCircle2, FileText, PackageCheck, Printer, UserRound } from "lucide-react";
import { prisma } from "@/lib/prisma";
import { PageHeader } from "@/components/page-header";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { LayawayLifecycleActions, LayawayPaymentForm } from "@/components/layaway-actions";
import { formatDate, formatLKR, toNum } from "@/lib/utils";
import { layawayBalance } from "@/lib/layaway";
import { LayawayJourney } from "@/components/layaway-journey";
export const dynamic = "force-dynamic";
const meta = { ACTIVE: { label: "Paying", tone: "blue" }, PAID_AWAITING_PICKUP: { label: "Paid · awaiting pickup", tone: "amber" }, RELEASED: { label: "Collected", tone: "green" }, CANCELLED: { label: "Cancelled", tone: "red" } } as const;
export default async function LayawayDetailPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ receipt?: string }> }) {
  const { id } = await params; const query = await searchParams;
  const order = await prisma.layawayOrder.findUnique({ where: { id }, include: { customer: true, items: true, payments: { include: { recordedBy: { select: { name: true } } }, orderBy: [{ paidDate: "desc" }, { createdAt: "desc" }] }, invoice: { select: { id: true, invoiceNumber: true } }, createdBy: { select: { name: true } } } });
  if (!order) notFound();
  const total = toNum(order.total), collected = toNum(order.collectedAmount), outstanding = layawayBalance(total, collected), pct = total ? Math.min(100, collected / total * 100) : 100, status = meta[order.status];
  return <div className="mx-auto max-w-5xl"><PageHeader title={`LAY-${String(order.orderNumber).padStart(6,"0")}`} subtitle={`${order.customer.name} · created ${formatDate(order.createdAt)}`} action={<Badge tone={status.tone} className="px-3 py-1.5">{status.label}</Badge>}/>
    {query.receipt && <div className="mb-4 flex items-center justify-between rounded-xl border border-primary/20 bg-primary-soft p-3 text-sm text-primary-ink"><span><CheckCircle2 className="mr-2 inline h-4 w-4"/>Layaway created and initial installment recorded.</span><Link href={`/layaways/${id}/receipts/${query.receipt}`}><Button size="sm"><Printer className="h-4 w-4"/>Receipt</Button></Link></div>}
    <section className="mb-4 overflow-hidden rounded-2xl border border-primary/20 bg-surface shadow-sm"><div className="border-b border-primary/15 bg-primary-soft/30 px-4 py-4 sm:px-6"><LayawayJourney activeStep={order.status==="RELEASED"?3:order.status==="PAID_AWAITING_PICKUP"?2:order.status==="ACTIVE"?1:0}/></div><div className="p-4 sm:p-6"><div className="grid grid-cols-2 gap-3 sm:grid-cols-3"><div className="col-span-2 border-b border-border-subtle pb-3 sm:col-span-1 sm:border-0 sm:pb-0"><p className="text-[10px] font-bold uppercase text-muted">Fixed total</p><p className="mt-1 font-mono text-lg font-extrabold sm:text-xl">{formatLKR(total)}</p></div><div><p className="text-[10px] font-bold uppercase text-muted">Collected</p><p className="mt-1 font-mono text-base font-extrabold text-primary sm:text-xl">{formatLKR(collected)}</p></div><div><p className="text-[10px] font-bold uppercase text-muted">Balance</p><p className="mt-1 font-mono text-base font-extrabold sm:text-xl">{formatLKR(outstanding)}</p></div></div><div className="mt-4 h-3 overflow-hidden rounded-sm bg-border-subtle"><div className="h-full bg-primary transition-all" style={{width:`${pct}%`}}/></div><div className="mt-2 flex justify-between gap-3 text-xs text-muted"><span>{pct.toFixed(0)}% paid</span><span className="text-right">{order.status === "RELEASED" ? "Goods handed over" : "Goods remain reserved in-store"}</span></div></div></section>
    <div className="grid gap-4 lg:grid-cols-[minmax(0,1.4fr)_minmax(18rem,.6fr)]"><div className="space-y-4">
      <Card><CardHeader><CardTitle>Reserved items</CardTitle></CardHeader><CardContent className="p-0">{order.items.map((item)=><div key={item.id} className="flex items-start justify-between gap-3 border-b border-border-subtle px-4 py-4 last:border-0"><div><p className="font-bold">{item.nameSnapshot}</p><p className="font-mono text-xs text-muted">{item.codeSnapshot} · {item.qty} × {formatLKR(item.unitPrice)}</p></div><p className="font-mono font-bold">{formatLKR(item.lineTotal)}</p></div>)}</CardContent></Card>
      <Card><CardHeader><CardTitle>Payment timeline</CardTitle></CardHeader><CardContent className="p-0">{order.payments.length===0?<div className="px-5 py-10 text-center text-sm text-muted">No installments recorded yet.</div>:order.payments.map((payment)=><div key={payment.id} className="flex items-center justify-between gap-3 border-b border-border-subtle px-4 py-4 last:border-0"><div><p className="font-mono font-bold text-primary">{formatLKR(payment.amount)}</p><p className="text-xs text-muted">{formatDate(payment.paidDate)} · {payment.method}{payment.reference?` · ${payment.reference}`:""} · {payment.recordedBy?.name??"Staff"}</p></div><Link href={`/layaways/${id}/receipts/${payment.id}`}><Button size="icon" variant="outline" aria-label={`Print receipt ${payment.receiptNumber}`}><Printer className="h-4 w-4"/></Button></Link></div>)}</CardContent></Card>
    </div><aside className="space-y-4">
      <Card><CardHeader><CardTitle>Customer & promise</CardTitle></CardHeader><CardContent className="space-y-3 text-sm"><p className="flex items-center gap-2 font-bold"><UserRound className="h-4 w-4 text-primary"/><Link href={`/customers/${order.customerId}`} className="hover:underline">{order.customer.name}</Link></p><p className="text-muted">{order.customer.phone}</p>{order.promisedPickupDate&&<p className="flex items-center gap-2"><CalendarClock className="h-4 w-4 text-clay"/>Promised {formatDate(order.promisedPickupDate)}</p>}{order.notes&&<p className="rounded-xl bg-input p-3 text-muted">{order.notes}</p>}{order.cancelReason&&<p className="rounded-xl bg-danger-soft p-3 text-danger-ink">Cancelled: {order.cancelReason}</p>}{order.invoice&&<Link href={`/invoices/${order.invoice.id}`}><Button variant="outline" className="w-full"><FileText className="h-4 w-4"/>{order.invoice.invoiceNumber}</Button></Link>}</CardContent></Card>
      {order.status==="ACTIVE"&&<Card><CardHeader><CardTitle>Record installment</CardTitle></CardHeader><CardContent><LayawayPaymentForm orderId={id} outstanding={outstanding}/></CardContent></Card>}
      {(order.status==="ACTIVE"||order.status==="PAID_AWAITING_PICKUP")&&<Card className={order.status==="PAID_AWAITING_PICKUP"?"border-clay/40":""}><CardHeader><CardTitle>{order.status==="PAID_AWAITING_PICKUP"?"Ready to hand over":"Order actions"}</CardTitle></CardHeader><CardContent>{order.status==="PAID_AWAITING_PICKUP"&&<p className="mb-3 flex gap-2 rounded-xl bg-clay-soft p-3 text-sm text-clay-ink"><PackageCheck className="h-4 w-4 shrink-0"/>Count and hand over the reserved goods. The final invoice is created only at this step.</p>}<LayawayLifecycleActions orderId={id} canRelease={order.status==="PAID_AWAITING_PICKUP"} hasPayments={order.payments.length>0}/></CardContent></Card>}
    </aside></div>
  </div>;
}
